### PR TITLE
MATH... and screen info

### PR DESCRIPTION
**Pull request by JanluOfficial**
math.* functions, see the javascript for all of them

system.screen() to fetch screen info, including aspect ratio, which requires math.gdc(a,b) to work

### CODE REVIEW

**Comment by MTSyntho** [comment]
seems good, although ill keep this open till i can fix bugs in the big-changes branch

**Comment by MTSyntho** [comment]
do you mind fixing the conflicts, idk how ;-;

**Comment by JanluOfficial** [comment]
looking into it

**Comment by JanluOfficial** [comment]
Quicky pushed webwin too since its better if everything goes through in one

**Comment by MTSyntho** [comment]
@JanluOfficial i think your pr had an outdated python script
im gonna add the new script again, can you update your py script as well?

**Pull request merged**
