### PR TITLE
A bunch of additions

### PR DESCRIPTION
**Pull request by JanluOfficial**
- Additional SDK math functions
- element.get() and isElement attribute for objects created with element.create()
- margin functions with capitalized directions (marginLeft to go along with marginleft) for more seamless development
- New Sound System + custom created login sound
- loadTheme() and unloadTheme() reimplemented due to some issues.

### CODE REVIEW

**Comment by JanluOfficial** [comment]
I quickly uncommented system.screen() and also set the HTML page to black due to a bug with the animations that seems to be semi-fixed with this.

**Comment by JanluOfficial** [comment]
Just added theme switching buttons to AzuTheme, plus actual button styling

**Comment by MTSyntho** [comment]
sorry for the long wait, ive been struggling with submitting changes from my pc to github ;-;

**Comment by MTSyntho** [comment]
alright so all has been merged, although it hasnt yet been tested, i may make a few changes (likely to my changes not yours) due to changes youve introduced for margins in the sdk

**Comment by MTSyntho** [comment]
other than the new wallpaper in dark mode imo 🥶
all is good 👍

**Pull request merged**
